### ISSUE TITLE
Customisable auto-refresh interval

### ISSUE THREAD

**Issue by danybony** [novoda/peepz#2]
The user should be able to choose the picture refresh interval among some predefined ones

**Comment by ouchadam** [comment]
I propose

```
how often should the picture take?

  - sometimes (5 minutes~?)
  - {quirky name} 2 minutes~
  - {quirky name} 1 minute~ 
  - custom within a range
```

**Comment by florianmski** [comment]
Honestly I don't really see the use of this.
Don't we just want this because it was in Pukka?
Who use it and for what purpose? (Just curious)

**Comment by ouchadam** [comment]
👍 we should find out if this would be useful or enforce a default

**Comment by jackSzm** [comment]
I would enforce by default. Don't give user too many options 👻

**Comment by ataulm** [comment]
👍  maybe different based on client (longer interval on mobile devices for example) but agree, maybe it's just because it was on Pukka.

Probably the workshop could help decide whether this is useful/wanted?

**Comment by tasomaniac** [comment]
I personally don't like 2 mins. It's too often. I was using 5min on Pukka and really liked it.

**Comment by caroinberlin** [comment]
So I threw this feature in the earlier designs. The idea was to be able to adjust how often your picture is taken because some people like the 30 seconds because it's raw unretouched real life unfolding, and for others it can be uncomfortable :-D  However unlike Pukka  I didnt want to put a specific number on it - it would be cool to have a choice between a "more often" and a "less often" picture take. I initially had 4 time options, but I think it would be better to go with 2. Like 1 minute and 5 minutes and thats it!

**Comment by ataulm** [comment]
done on android - as 2min, 5min and off (manual).

**Comment by ouchadam** [comment]
done for web as well 👍
